### ISSUE TITLE
Selenium Problem

### ISSUE THREAD

**Issue by SebastianMoyano** [SHUR1K-N/MeetNinja-Google-Meet-Bot#20]
Hi, i cant manage to get the share screen function to work with the chrome browser.
I dont know if i have to add a new flag or something, i tried with --enable-usermedia-screen-capturing, --allow-http-screen-capture and  --check-screen-recording-permission but nothing,
any advise would be greatly receive thanks!

**Comment by SHUR1K-N** [comment]
Since this is a custom implementation that you are trying, it is not an Issue. Kindly, raise your question(s) on a platform such as Stack Overflow. I am sure they would know and help.

PS: I have also personally moved on from this project, and do not wish to invest additional time within it unless it is an actual Issue that hinders this tool's workings. Sorry, and all the best!
