### ISSUE TITLE
record the meetings

### ISSUE THREAD

**Issue by JulesGM** [SHUR1K-N/MeetNinja-Google-Meet-Bot#21]
Hello,
Is there any way to get this to record the meetings?
Thanks.

**Comment by SHUR1K-N** [comment]
Since this is a custom implementation that you are trying, it is not an Issue. Kindly, raise your question on a platform such as Stack Overflow. I am sure they would know and help.

PS: I have also personally moved on from this project, and do not wish to invest additional time within it unless it is an actual Issue that hinders this tool's workings. Sorry, and all the best!
