### ISSUE TITLE
I have done till this..Help please

### ISSUE THREAD

**Issue by reeswar21** [SHUR1K-N/MeetNinja-Google-Meet-Bot#27]
Initializing browser...Traceback (most recent call last):
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 238, in <module>
    driver = initBrowser()
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 117, in initBrowser
    driver = webdriver.Chrome(service=servicePath, options=chromeOptions)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 270, in <module>
    print(e)
NameError: name 'e' is not defined
>>>

**Comment by reeswar21** [comment]
I have already downloaded meet ninja back again and done all the steps till print (e)

**Comment by SHUR1K-N** [comment]
You keep opening the same Issue with the same traceback over and over again...

As already discussed, this can _only_ be fixed by providing the correct permissions using `chmod` which your machine seems to be having a problem with. This Issue has already been solved in previous threads (also pinned within MeetNinja's Issues page with the [SOLVED] tag), and there is just no other way except the permissions. Please do some research as to why your `chmod` command is not providing the desired output, and only then would you be able to get past this error.

**This is _not_ a problem with MeetNinja.**

**Comment by reeswar21** [comment]
May I know until what version does the chromedriver support for meet ninja

**Comment by reeswar21** [comment]
I suppose something wrong with chromedriver and chrome version

**Comment by SHUR1K-N** [comment]
As long as the version of chromedriver you have is compatible with the particular version of Google Chrome you are currently on, MeetNinja will run entirely fine (tested on multiple UNIX and Windows machines on the latest versions).

There is definitely nothing wrong with MeetNinja itself; it is your particular machine that is somehow having an issue with changing permissions.
