### ISSUE TITLE
Google blocks automated bots from logging into Gmail - [SOLVED]

### ISSUE THREAD

**Issue by dproyt** [SHUR1K-N/MeetNinja-Google-Meet-Bot#5]
hey my bot just opens the incognito or the guest mode in chrome due to which i cant login any fixes

**Comment by SHUR1K-N** [comment]
Check all the steps in the ['Usage' section](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot#usage), specifically step [#3](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot#usage); **you need to substitute all your details (including your Gmail account address and password) into the program before running it**!

**Comment by dproyt** [comment]
yea i did it but same problem

**Comment by SHUR1K-N** [comment]
Strange, could you share a screenshot of what it shows you in the generated web browser, and also a screenshot of the MeetNinja console window when you face this issue?

**Comment by dproyt** [comment]
[ice_video_20201116-195352.zip](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/files/5546832/ice_video_20201116-195352.zip)

**Comment by SHUR1K-N** [comment]
A similar issue has been raised before, you may check it out [here](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/issues/2). Long story short though, Google does not trust new devices being logged in from, or newly created e-mail addresses being used; or even both. Check the mentioned Issue thread out and try confirming by using MeetNinja on a device that _has_ been used to before for the sign-in process (so it is trusted by Google), and also make sure a freshly created or incorrect e-mail is not being used to to sign in.

I will leave this thread open for a day or two and only close it upon inactivity. Feel free to share your progress or further issues here until then!

**Comment by dproyt** [comment]
no its my main account i have logged in before this attempt and same issue exists if there is any code that opens normal mode intead of incognito

**Comment by SHUR1K-N** [comment]
If it is as you said and this happens when you execute any browser automation code that opens the browser in Incognito, you can try commenting out or removing [line #104](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/blob/24b92d39c9072c963cfdefe8f039216c31702f1d/MeetNinja.py#L104) from MeetNinja.py, which is responsible for opening Chrome in Incognito mode:

`chromeOptions.add_argument("--incognito")`

If Incognito is _indeed_ the culprit here, then this line-removal _should_ fix it. However, it should not be the case since MeetNinja has already been tested _with_ Incognito across multiple accounts and devices. Anyway, _do_ report back, comrade!

**Comment by dproyt** [comment]
incognito is gone guest mode is on now its preventing sign in

**Comment by dproyt** [comment]
i removed the line #104

**Comment by SHUR1K-N** [comment]
**This is most likely Google just not trusting your sign-in.** Are you on a mobile hotspot connection or a dynamic IP address? Also, have you tried everything in the "possible fixes" section when MeetNinja fails (especially making sure you have the latest version of Chrome installed and also the latest web driver (Chromedriver)?

**Comment by dproyt** [comment]
yes i have latest chrome and drivers im using a router  i havent tried that meetninja fsil could u link it

**Comment by SHUR1K-N** [comment]
If what you are referring to is the "possible fixes" section, then it is a printed message shown in the MeetNinja console window itself upon failure. If you have tried everything in that list, one final thing I can suggest is try to run the Python script by double-clicking on MeetNinja.py in the file explorer itself instead of running it via VSCode; see if it changes anything.

Also, could you share a screenshot of your substituted values **(with your e-mail and password carefully censored/redacted)**?

**Comment by dproyt** [comment]
no running outside vs didnt make any difference i tried the solution  proived by the program didnt change
![github](https://user-images.githubusercontent.com/74549153/99276519-c0159000-2852-11eb-8a60-d493c708661d.PNG)

**Comment by SHUR1K-N** [comment]
Then it is 100% just that Google is not being able to trust your sign-in, possibly due to Google somehow taking this as a new device or IP or location. You should try multiple _regular_ successful sign-ins on this device, and then probably revisit MeetNinja later on when Google may have bestowed your device/IP with sufficient trust.

**Comment by dproyt** [comment]
man i tried with my school mail and it worked thanks mate for ur help

**Comment by SHUR1K-N** [comment]
Is it a G-Suite e-mail address provided to you by your institution?

**Comment by dproyt** [comment]
yepp

**Comment by SHUR1K-N** [comment]
It makes sense! All accounts that were tested for MeetNinja _were_ G-Suite accounts (did not quite think this could have been a factor).

**Possible Reason:**
Apparently, G-Suite accounts seem to have customized security settings that the G-Suite _administrator_ is in charge of instead of Google's standard security. Since G-Suite security is another added bit of configuration our institutions would have to _explicitly_ customize, they probably just leave the security setting(s) to something along the lines of "allow all devices/IPs to sign in".
### [SOLVED]

**Comment by dproyt** [comment]
yo bro the bot joins the classes and leaves too but when it leaves the class it encounters some error and bot stops although it has left the class but it says leaving meet failed any fixes

**Comment by SHUR1K-N** [comment]
You may open a separate new Issue of its _own_ for this specific issue so it is more organized for other users. I′ll be able to help you there.

**Comment by KeparYTbcc** [comment]
i have a G-Suite
(google of my school)
but when i enter, they redirect to a special login page,
look try to loggin to:
123@cslaval.qc.ca
Possible to code something to log on it, i will pay you after, if needed

**Comment by SHUR1K-N** [comment]
@KeparYTbcc: You will either have to give me a valid e-mail address for me to check this personally, or at least share an image of the "special login page" you have mentioned for me to get an idea of what it is; because "123@cslaval.qc.ca" is not a valid e-mail address and it would not allow me to get to the special page you intend to show me.

**Comment by KeparYTbcc** [comment]
> @KeparYTbcc: You will either have to give me a valid e-mail address for me to check this personally, or at least share an image of the "special login page" you have mentioned for me to get an idea of what it is; because "[123@cslaval.qc.ca](mailto:123@cslaval.qc.ca)" is not a valid e-mail address and it would not allow me to get to the special page you intend to show me.

1583277@cslaval.qc.ca

**Comment by KeparYTbcc** [comment]
here is my valid one 
Sorry for long time reply, dint recieve an notification about yout reply

**Comment by SHUR1K-N** [comment]
> > @KeparYTbcc: You will either have to give me a valid e-mail address for me to check this personally, or at least share an image of the "special login page" you have mentioned for me to get an idea of what it is; because "[123@cslaval.qc.ca](mailto:123@cslaval.qc.ca)" is not a valid e-mail address and it would not allow me to get to the special page you intend to show me.
> 
> [1583277@cslaval.qc.ca](mailto:1583277@cslaval.qc.ca)

I did check it out and indeed, it led me to a special page (never seen something like this before!), but the page keeps timing out and does not load. Are you sure the domain is functional as of yet?

**Comment by KeparYTbcc** [comment]
ya, u just need to be connected to a canada,montreal VPN
or network

**Comment by KeparYTbcc** [comment]
( i think)

**Comment by SHUR1K-N** [comment]
> ya, u just need to be connected to a canada,montreal VPN
> or network

Ah, I see. Well, in that case, I unfortunately would not be able to help, partner; since I would not be able to test this issue and work on it if necessary.

**Comment by KeparYTbcc** [comment]
OOF

**Comment by KeparYTbcc** [comment]
u have discord @SHUR1K-N ?
