### ISSUE TITLE
ACTUALLY I CANT HEAR ANYTHING IN MEET WHEN I GO TO SETTINGS IT SHOWS SPEAKERS ARE BLOCKED

### ISSUE THREAD

**Issue by dproyt** [SHUR1K-N/MeetNinja-Google-Meet-Bot#8]
ACTUALLY I CANT HEAR ANYTHING IN MEET WHEN I GO TO SETTINGS IT SHOWS SPEAKERS ARE BLOCKED

**Comment by SHUR1K-N** [comment]
This is not the issue you were referring to. Your issue is of some pop-up related failure; be specific, it helps with organization and helps other users that may have similar issues in the future. Many users may actually see your Issue thread(s), so try to make them comprehensible and of better quality.

Anyway, again, you may open a separate Issue thread for **this specific issue**. Your speakers issue does not have anything to do with this.
